version: "3.9"
services:
  pfa-server:
    build: ./A_PFAServer
    image: fabreguesm/projectflexxagent-server:1.2.0
    ports:
      - "${SERVER_PORT:-8000}:8000"
    env_file:
      - ./A_PFAServer/config/.env
    environment:
      DB_ENGINE: "${DB_ENGINE:-postgresql}"
      DB_HOST: "${DB_HOST:-localhost}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_NAME: "${DB_NAME:-ferrocons_db}"
      DB_USER: "${DB_USER:-eriodanieldiaz}"
      DB_PASSWORD: "${DB_PASSWORD:-changeme}"
      ADMIN_DB_USER: "${ADMIN_DB_USER:-eriodanieldiaz}"
      ADMIN_DB_HOST: "${ADMIN_DB_HOST:-localhost}"
      ADMIN_DB_PORT: "${ADMIN_DB_PORT:-5432}"
      ADMIN_DB_NAME: "${ADMIN_DB_NAME:-CognitivaAI}"
      ADMIN_DB_PASSWORD: "${ADMIN_DB_PASSWORD:-changeme}"
      MCP_DISCOVERY_ENABLED: "${MCP_DISCOVERY_ENABLED:-true}"
      MCP_SERVERS: "${MCP_SERVERS:-aulas_demo,ferrocons_data}"
      MCP_LAUNCH_FILE: "${MCP_LAUNCH_FILE:-/Users/eriodanieldiaz/Desktop/FlexxAgent/Server/mcp_config.json}"
      SESSION_TOKEN_EXPIRY_SECONDS: "${SESSION_TOKEN_EXPIRY_SECONDS:-86400}"
      RESEND_API_KEY: "${RESEND_API_KEY:-}"
      EMAIL_FROM_ADDRESS: "${EMAIL_FROM_ADDRESS:-info@cognitivaai.com}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME:-Cognitiva AI}"
      SERVER_VERSION: "${SERVER_VERSION:-1.0.0.0}"
      BUILD_NUMBER: "${BUILD_NUMBER:-0}"
    volumes:
      - server-logs:/app/logs
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q ${SERVER_HEALTHCHECK_URL:-http://localhost:8000/health} || echo 'Health check failed but continuing...'"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 120s
  pfa-client:
    build:
      context: ./D_PFAShadCNClient
      args:
        SERVER_BASE_URL: "${SERVER_BASE_URL:-http://10.250.0.68:8000}"
        FRONTEND_BASE_URL: "${FRONTEND_BASE_URL:-}"
        PORT: "${PORT:-3755}"
    image: fabreguesm/projectflexxagent-cliente:1.2.0
    ports:
      - "${PORT:-3755}:3755"
    environment:
      PORT: "${PORT:-3755}"
      SERVER_BASE_URL: "${SERVER_BASE_URL:-http://10.250.0.68:8000}"
      FRONTEND_BASE_URL: "${FRONTEND_BASE_URL:-}"
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider ${CLIENT_HEALTHCHECK_URL:-http://localhost:4375} || echo 'Client health check failed but continuing...'"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 120s
networks:
  traefik:
    external:
      name: traefik
volumes:
  server-logs:
