version: "3.9"
services:
  pfa-server:
    build: ./A_PFAServer
    image: fabreguesm/projectflexxagent-server:1.0.4
    ports:
      - "${SERVER_PORT:-8000}:8000"
    
    environment:
      DB_ENGINE: "${DB_ENGINE:-postgresql}"
      DB_HOST: "${DB_HOST:-10.250.0.68}"
      DB_PORT: "${DB_PORT:-5003}"
      DB_NAME: "${DB_NAME:-ferrocons_db}"
      DB_USER: "${DB_USER:-flexxus}"
      DB_PASSWORD: "${DB_PASSWORD:-Flexxus2023**}"
      ADMIN_DB_USER: "${ADMIN_DB_USER:-flexxus}"
      ADMIN_DB_HOST: "${ADMIN_DB_HOST:-10.250.0.68}"
      ADMIN_DB_PORT: "${ADMIN_DB_PORT:-5002}"
      ADMIN_DB_NAME: "${ADMIN_DB_NAME:-CognitivaAI}"
      ADMIN_DB_PASSWORD: "${ADMIN_DB_PASSWORD:-Flexxus2023**}"
      MCP_DISCOVERY_ENABLED: "${MCP_DISCOVERY_ENABLED:-true}"
      MCP_SERVERS: "${MCP_SERVERS:-aulas_demo,ferrocons_data}"
      MCP_LAUNCH_FILE: "${MCP_LAUNCH_FILE:-/Users/eriodanieldiaz/Desktop/FlexxAgent/Server/mcp_config.json}"
      SESSION_TOKEN_EXPIRY_SECONDS: "${SESSION_TOKEN_EXPIRY_SECONDS:-86400}"
      RESEND_API_KEY: "${RESEND_API_KEY:-}"
      EMAIL_FROM_ADDRESS: "${EMAIL_FROM_ADDRESS:-info@cognitivaai.com}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME:-Cognitiva AI}"
    volumes:
      - server-logs:/app/logs
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]  
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://10.250.0.68:8000/health || echo 'Health check failed but continuing...'"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 120s

  pfa-client:
    build: ./D_PFAShadCNClient
    image: fabreguesm/projectflexxagent-cliente:1.0.7
    ports:
      - "${PORT:-3755}:3755"

    environment:
      PORT: "${PORT:-3755}"
      SERVER_URL: "${SERVER_URL:-http://10.250.0.68:8000}"
      SERVER_PORT: "${SERVER_PORT:-8000}"
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://10.250.0.68:3755 || echo 'Client health check failed but continuing...'"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 120s
    deploy:
      placement:
        constraints: ["${NODE}"]
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}        
  
networks:
  traefik:
    external:
      name: traefik
volumes:
  server-logs:
